### ISSUE TITLE
Visual features depth

### ISSUE THREAD

**Issue by TotoPaolillo** [EnricoMingo/opensot_visual_servoing#14]
At the moment, we publish a random value as depth of the visual features. If not properly computed, this field should be empty and handled on the control side (for example, we might choose to use the depth of the visual features at the target position).

**Comment by TotoPaolillo** [comment]
One way to handle this issue could be to pass the depths as parameter of the image processing block, and then publish.

**Comment by EnricoMingo** [comment]
We now adopt the depth of the measured features in ```on_features_recv(...)``` in the CartesI/O support.
