### ISSUE TITLE
Point projection

### ISSUE THREAD

**Issue by TotoPaolillo** [EnricoMingo/opensot_visual_servoing#6]
In order to test a simulated environment, we need to implement a function that, given the current pose of the camera, projects the cartesian points on the image plane. 
This function is required also for the intialization and it is useful in other practical situations.

**Comment by TotoPaolillo** [comment]
First test (ViSP code integration) implemented. Things to be discussed/understood/fixed:
- how `addFeature` can work without `selectFeatures`? I guess it works only for `pointFeatures` and not `basicFeatures`. 
- I had to implement a function `clearFeatures` to be used with `addFeatures`. Maybe a cleaner way is to use 'setFeatures`
- I couldn't understand how the projection could work without (explicitly) assign the camera intrinsic parameters.
- vpSimulatorCamera has been used (from ViSP) to simulate the camera motion.
- I added the function `eigen2visp` (take from visp) in `VisualServoing` class: 1) maybe it has to be put in utils; 2) why couldn't we include it directly from ViSP?
- Important: be careful on how to set the depth of the point, now it has been neglected.

**Comment by EnricoMingo** [comment]
- Nope, select has default value vpBasicFeature::FEATURE_ALL
- if task update() is called directly after clearFeatures() the A matrix and b vector are set to zeros
- moved all ```eigen2visp``` and ```visp2eigen``` functions to ```Utils.h```
