### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by TotoPaolillo** [EnricoMingo/opensot_visual_servoing#8]

**Comment by TotoPaolillo** [comment]
To make comilation possible, I had to comments the lines relative to getBaseLink() and getCameraLink() in the code of the tests.

Moreover, we had to add "find_package(cartesian_interface)" in CMakeLists.txt

**Comment by EnricoMingo** [comment]
This is due to an update of OpenSoT. I will keep this issue open to remember to create new debians.

**Comment by EnricoMingo** [comment]
Solved
