### ISSUE TITLE
Sign of the VS control law

### ISSUE THREAD

**Issue by TotoPaolillo** [EnricoMingo/opensot_visual_servoing#9]
In the test, to make the simulation working, I had to add a minus ("-") in the control law:

cam_vel = - L_ping * b

Normally, we shouldn't need it.

**Comment by EnricoMingo** [comment]
I found the problem:
you where using ```setFeatures(generic_desired_features, generic_curr_features, feature_selection)``` but ```bool VisualServoing::setFeatures(std::list<vpBasicFeature *>& feature_list,
                 std::list<vpBasicFeature *>& desired_feature_list,
                 std::list<unsigned int>& feature_selection_list)```. Basically you where inverting actual with desired feature lists.
Fixed, I am going to close this.
